# Generated by Django 4.2.6 on 2023-11-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_alter_role_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='label',
            field=models.TextField(choices=[(1, 'Adminstrateur'), (2, 'Professeur'), (3, 'Etudiant')], default=3, max_length=1),
        ),
    ]
